spring:
  application:
    name: InformationSystem
    
server:
  port: 8094
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka
  instance:
    metadataMap:
      connectionType: synchronous