PREFIX : <http://pros.upv.es/pvalderas/IoTDevices>
PREFIX sosa: <http://www.w3.org/ns/sosa/> 
ASK WHERE {  
	?s a :TemperatureSensor . 
	?o a sosa:Observation . 
	?s sosa:madeObservation ?o . 
	?o sosa:observebProperty :Temperature . 
	?o sosa:hasResult ?result . 
	?result :temperatureCondition "TooWarm" .
}