PREFIX : <http://pros.upv.es/pvalderas/IoTDevices>
PREFIX sosa: <http://www.w3.org/ns/sosa/> 
ASK WHERE { 
	?s a :PresenceSensor . 
	?o a sosa:Observation . 
	?s sosa:madeObservation ?o . 
	?o sosa:hasFeatureOfInterest ?f . 
	?f a :Container . 
	?o sosa:hasResult ?result . 
	?result :status "arrivalInWarehouse" .
}