spring:
  application:
    name: Robot
    
server:
  port: 8095
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka
  instance:
    metadataMap:
      connectionType: synchronous