spring:
  application:
    name: BPController
    
server:
  port: 8081
  
actionPerformer: 
  serviceUrl: http://localhost:8082/iot/microservice
  name: ActionPerformer
  
contextMonitor:
    serviceUrl: http://localhost:8083
    conditionPath: /context/query
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka
    registerWithEureka: true
    fetchRegistry: true

eventBus:
  type: rabbitmq
  host: localhost